version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    target-branch: dev
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
    open-pull-requests-limit: 5
    target-branch: dev
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
