name: skipify-tshirt-store-demo
services:
- name: skipify-demo
  source_dir: /deploy
  github:
    repo: nick-suess-skipify/skipify-sdk-test-app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: PORT
    value: "8080"
  - key: SKIPIFY_MERCHANT_ID
    value: "1bdc8b60-6dd4-4126-88e1-c9e5b570f1a0"
  - key: SKIPIFY_ENVIRONMENT
    value: "stage"
  - key: NODE_ENV
    value: "production"
  build_command: npm install

domains:
- domain: skipify-tshirt-store-demo.ondigitalocean.app
  type: PRIMARY
