name: skipify-tshirt-store-demo
services:
- name: skipify-demo
  source_dir: /deploy
  github:
    repo: nick-suess-skipify/skipify-sdk-test-app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: PORT
    value: "8080"
  - key: NODE_ENV
    value: "production"
  - key: SKIPIFY_ENVIRONMENT
    value: "stage"
  - key: SECURITY_ENABLED
    value: "true"
  # 🔐 CRITICAL SECURITY: The following variables MUST be set in Digital Ocean dashboard
  # ⚠️  DO NOT commit sensitive values to GitHub - set these in DO App Platform:
  # 
  # REQUIRED: Set this in Digital Ocean App Platform Environment Variables:
  # SKIPIFY_MERCHANT_ID: <your_skipify_merchant_id>
  #
  # 📋 Instructions:
  # 1. Go to Digital Ocean App Platform
  # 2. Select your app → Settings → App-Level Environment Variables
  # 3. Add SKIPIFY_MERCHANT_ID with your actual merchant ID
  # 4. Redeploy the application
  #
  # 🚨 NEVER commit real values to this file!
  build_command: npm install --only=production

# Security: HTTPS only
domains:
- domain: skipify-tshirt-store-qbcx3.ondigitalocean.app
  type: PRIMARY
  
# Additional security configurations
alerts:
- rule: CPU_UTILIZATION
  value: 80
- rule: MEM_UTILIZATION  
  value: 80