name: skipify-tshirt-store-demo
services:
- name: skipify-demo
  source_dir: /deploy
  github:
    repo: nick-suess-skipify/skipify-sdk-test-app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: PORT
    value: "8080"
  # CRITICAL SECURITY: These must be set in Digital Ocean dashboard
  - key: SKIPIFY_MERCHANT_ID
    value: "1bdc8b60-6dd4-4126-88e1-c9e5b570f1a0"
  - key: SKIPIFY_ENVIRONMENT
    value: "stage"
  - key: NODE_ENV
    value: "production"
  # Additional security settings
  - key: SESSION_SECRET
    value: "CHANGE_THIS_IN_PRODUCTION_TO_RANDOM_STRING"
  - key: SECURITY_ENABLED
    value: "true"
  build_command: npm install --only=production

# Security: HTTPS only
domains:
- domain: skipify-tshirt-store-qbcx3.ondigitalocean.app
  type: PRIMARY
  
# Additional security configurations
alerts:
- rule: CPU_UTILIZATION
  value: 80
- rule: MEM_UTILIZATION  
  value: 80