version: 2.1

orbs:
  gcr: circleci/gcp-gcr@0.7.1
  gke: circleci/gcp-gke@1.4.0
  node: circleci/node@5.0.2
  # gcp-storage: freighthub/gcp-storage@0.2.0

jobs:
  code-quality:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: medium
    steps:
      - checkout

      - node/install:
          node-version: '16.13'

      - run:
          name: Install dependencies
          command: |
            npm i

      - run:
          name: Lint code
          command: |
            npm run lint:scripts

      # - run:
      #     name: Run tests
      #     command: npm run test:cov -- --coverageReporters=lcov

      # - run:
      #     name: Send coverage report to coveralls
      #     when: always
      #     command: cat ./coverage/lcov.info | npx coveralls

  build-dev:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: medium
    steps:
      - checkout
      - gcr/gcr-auth
      - node/install:
          node-version: "16.13"

      - run:
          name: Install dependencies
          command: |
            gcloud auth print-access-token
            npm i

      - run:
          name: 'build code base'
          command: npm run build:development
      - store_artifacts:
         path: dist

  build-push-dev:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: medium
    steps:
      - checkout
      - gcr/gcr-auth
      - node/install:
          node-version: "16.13"

      - run:
          name: Install dependencies
          command: |
            npm i
            gcloud auth print-access-token

      - run:
          name: "build code base"
          command: npm run build:development
      - store_artifacts:
          path: dist
      # - gcp-storage/upload:
      #     source_path: dist/*
      #     destination_bucket: skipfyscript
      #     destination_prefix: sdk/
      #     cache_control: "public, max-age=86400"
      #     transfer_files_compressed: "js"

      

  # build-push-stage:

  # build-push-prod:

workflows:
  always:
    jobs:
      - code-quality:
          context: skipify-dev
      - build-dev:
          context: skipify-dev
          requires:
            - code-quality
  dev:
    jobs:
      - build-approval:
          type: approval
      - code-quality:
          context: skipify-dev
          requires:
            - build-approval
      - build-push-dev:
          context: skipify-dev
          requires:
            - build-approval

