version: 2.1

orbs:
  gcr: circleci/gcp-gcr@0.15.1
  node: circleci/node@5.1.0
  gcp-cli: circleci/gcp-cli@3.0.1

jobs:
  code-quality:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: medium
    steps:
      - checkout

      - node/install:
          node-version: '16.13'

      - run:
          name: Install dependencies
          command: |
            npm i

      - run:
          name: Lint code
          command: |
            npm run lint:scripts

#      - run:
#          name: Run tests
#          command: npm run test:coverage -- --coverageReporters=lcov

#      - run:
#          name: Send coverage report to coveralls
#          when: always
#          command: cat ./coverage/lcov.info | npx coveralls

  build:
    parameters:
      branch:
        description: The branch we are building. i.e. dev, stage, or prod
        type: string
    machine:
      image: ubuntu-2004:202104-01
    resource_class: medium
    steps:
      - checkout
      - gcr/gcr-auth
      - node/install:
          node-version: "16.13"

      - run:
          name: Install dependencies
          command: |
            gcloud auth print-access-token
            npm i

      - run:
          name: "build code base"
          command: npm run build:<< parameters.branch >>

      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    parameters:
      bucket:
        description: Google Cloud Storage bucket name where artifact will be deployed to
        type: string
    executor: gcp-cli/default
    steps:
      - attach_workspace:
          at: .
      - gcp-cli/setup:
          version: 404.0.0
      - run:
          name: Push to bucket
          command: gsutil cp -r dist/* gs://<< parameters.bucket >>
      - run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployed checkout-sdk to << parameters.bucket >> env from circleci, version: https://github.com/deeperlooknetwork/checkout-sdk/commit/'"$(git rev-parse --short HEAD)"'"}' https://hooks.slack.com/services/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

workflows:
  always:
    jobs:
      - code-quality
      - build:
          branch: dev
          context: skipify-dev
          requires:
            - code-quality
  dev:
    jobs:
      - build-approval:
          type: approval
      - code-quality:
          requires:
            - build-approval
      - build:
          branch: development
          context: skipify-dev
          requires:
            - code-quality
      - deploy:
          name: deploy-dev
          bucket: checkout-sdk-dev
          context: skipify-dev
          requires:
            - build
  stage:
    jobs:
      - build-approval:
          type: approval
      - code-quality:
          requires:
            - build-approval
      - build:
          branch: staging
          context: skipify-stage
          requires:
            - code-quality
      - deploy:
          name: deploy-stage
          bucket: checkout-sdk-stage
          context: skipify-stage
          requires:
            - build
  prod:
    jobs:
      - build-approval:
          type: approval
      - code-quality:
          requires:
            - build-approval
      - build:
          branch: production
          context: skipify-prod
          requires:
            - code-quality
      - deploy:
          name: deploy-prod
          bucket: checkout-sdk
          context: skipify-prod
          requires:
            - build
